version: '3.8'

services:
  Web:
    image: flaskpostgre
    
  db:
    image: postgres:15.3
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=localhost
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flaskpostgre
